# ---------- TRAINING PARAMETERS ----------
train:
  train_batch_size: 1024
  total_steps: 2109
  learning_rate:
    warmup_steps: 820
    init_learning_rate: 0.64
    learning_rate_levels: [0.064, 0.0064]
    learning_rate_steps: [1641, 1992]

resnet:
  batch_norm:
    batch_norm_momentum: 0.9

fpn:
  batch_norm:
    batch_norm_momentum: 0.9

retinanet_head:
  batch_norm:
    batch_norm_momentum: 0.9
